### PR TITLE
Add exemplary docker stack with nginx as a reverse proxy for TLS/SSL support

### PR DESCRIPTION
**Pull request by GutZuFusss**
See #5 for information why I think this should be provided as a quality of life feature for developing. Really brings down the entry barrier.

The official, unmodified *Shakes & Fidget* client requires you to use SSL. To be more specific, all the URLs are hardcoded with a `https://` prefix, and it's a lot easier to set up a reverse proxy like nginx, since you can then simply use the *Shakes & Fidget* client as-is from the official [*Shakes & Fidget* website](https://sfgame.net). The only thing then left to do is to override the `https://sfgame.net/config.json` response in your browser, such that it returns the Nginx address (https://localhost:6768 in this example) as one of the servers. TODO: Add a step by step guide for people less experienced with advanced browser dev settings like this in the root README.

The reason to use a reverse proxy here is, that I think the concern of encryption should be separated from the main code, although I am aware that the used framework is capable of it.

I know right now it looks kind of random to have that directory there in the first place, and it's even weirder, that it is a docker stack with only one container. You might say YAGNI, but personally I am also running the Postgres server in Docker, and I think I will add that to the stack next.
Ultimately of course, we might also have a Dockerfile to build a sf-server into a Docker image itself. That is of course for the far, far future, but why not start now with quality of life features for developers?

Thanks for coming to my TED talk.

### CODE REVIEW

**Comment by the-marenga** [comment]
Thanks! This is a big step towards actually making this useable. I merged a bunch of changes from the dev-branch, you might want to check that out. Should not effect this PR though. Among other things, I added my firefox dev extension, which alters the config.json in that PR. I personally use cloudflare tunnel and just point a valid domain to my localhost, but doing it with docker container seems like a more general solution. 

I have no issues merging this, but if you want to adjust your documentation before that, let me know

**Comment by GutZuFusss** [comment]
> Thanks! This is a big step towards actually making this useable. I merged a bunch of changes from the dev-branch, you might want to check that out. Should not effect this PR though. Among other things, I added my firefox dev extension, which alters the config.json in that PR. I personally use cloudflare tunnel and just point a valid domain to my localhost, but doing it with docker container seems like a more general solution.
> 
> I have no issues merging this, but if you want to adjust your documentation before that, let me know

Sure, I can do the documentation too, but I'd like to wait until we discussed (or you looked into rather) https://github.com/the-marenga/sf-server/pull/8

**Comment by GutZuFusss** [comment]
@the-marenga Okay, I'm done writing documentation, I think this will do for now. Maybe I will sneak in a commit refining some things with future PRs, but overall I am pretty happy with how it turned out. But let me know what you think :)

**Comment by GutZuFusss** [comment]
Is GitHub bugging here? Wtf is that change history, showing changes that are already on master?

Not even pretending to know what is going on here, I was using GitHub desktop, actually crazy how fucked up that history is. Im just making a new PR (#11) instead, force pushing now will only further ruin this thread. 
Linking #11 here should be good enough in terms of tracability.

**Pull request closed without merging**
